FileVersion = 1
Projects = {AsmTool = {Path = "."}, ImGui = {Path = "Dependencies/imgui-beef/ImGui"}, RfgTools = {Path = "Dependencies/RfgTools"}, "Beef.Linq" = {Path = "Dependencies/Beef.Linq/src"}}
Unlocked = ["Zlib"]

[Workspace]
StartupProject = "AsmTool"

[Configs.Debug.Win64]
Toolset = "LLVM"
BfSIMDSetting = "SSE4"

[Configs.Release.Win64]
BfSIMDSetting = "SSE4"

[Configs.Paranoid.Win64]
BfSIMDSetting = "SSE4"

[Configs.Test.Win64]
BfSIMDSetting = "SSE4"
